name: Descomprimir proyecto

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Descomprimir proyecto
        run: |
          unzip -o statedge-ai.zip -d .
          rm statedge-ai.zip

      - name: Guardar archivos descomprimidos
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Descomprimir proyecto StatEdge AI"
          git push
